import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Topbar from "@/components/ui/topbar";
import { getUserById } from "@/lib/actions";
import Sidebar from "@/components/ui/sidebar";
import { ReduxProviders } from "@/lib/redux/provider";
import LogoutButton from "@/components/ui/logoutButton";
import Provider from "@/utils/provider";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Root Layout",
  description: "Generated by create next app",
  icons: "favicon.png",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { data: user } = await getUserById();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ReduxProviders>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex">
              <Sidebar logout={<LogoutButton />} />
              <div className="w-full mb-6">
                <Topbar user={user?.[0]} />
                <Provider>{children}</Provider>
                <Toaster />
              </div>
            </div>
          </ThemeProvider>
        </ReduxProviders>
      </body>
    </html>
  );
}
